# Generated by Django 2.2.7 on 2019-11-08 09:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nesting_level', models.IntegerField(verbose_name='Level of category')),
                ('name', models.CharField(max_length=100, verbose_name='Name of school')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code of product')),
                ('name', models.CharField(max_length=100, verbose_name='Name of school')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price of product')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity of product')),
                ('categories', models.ManyToManyField(related_name='products', to='products.Category')),
            ],
        ),
    ]
